### ISSUE TITLE
Translation File

### ISSUE THREAD

**Issue by yodhavee** [mechef/mechef#121]
English - [en-us.properties.zip](https://github.com/mechef/mechef/files/1566414/en-us.properties.zip)

Thai - [th-th.properties.zip](https://github.com/mechef/mechef/files/1566411/th-th.properties.zip)

Japan - [jp-jp.properties.zip](https://github.com/mechef/mechef/files/1585277/jp-jp.properties.zip)

**Comment by pptang** [comment]
It's downloaded already
