### ISSUE TITLE
[Menu Page] Dish and Ingredient cannot be created

### ISSUE THREAD

**Issue by Tzuzee** [mechef/mechef#206]
Returns ajax error 400

**Comment by Tzuzee** [comment]
Using new account

thuang058@gmail.com / mechef

**Comment by pptang** [comment]
@nkfly This bug results from api-side hasn't removed deliveryIdList validation

Here is the error message:

```
{"status":"fail","reason":"The following fields can not be null:  deliveryIdList"}
```
