### ISSUE TITLE
Users can create account for Back Office

### ISSUE THREAD

**Issue by yodhavee** [mechef/mechef#3]
Spec
-----
- User can account in the back office by providing the following information
  - First name
  - Last name
  - Email
  - Telephone number
- User need agree to terms and conditions before they can join
- User can click on term and condition link to open term and condition page

Error message
|Condition|Message|
|--|--|
|First name is empty|Please input your first name.|
|Last name is empty|Please input your last name.|
|Email is empty|Please input your email.|
|Email format is invalid|Email is incorrect, please double-check again.|
|Telephone is empty|Please input your telephone number.|
|Telephone format is invalid|Telephone number is incorrect, please double-check again.|

Mock Up
-----

Acceptance Criteria
-----
- [ ] User can create account when input all information and accept term and condition
- [ ] User cannot click `Join Now` button when 1 of the four field are not input
- [ ] User cannot click `Join Now` when they do not accept term and condition.
- [ ] Display error message

User Story 1 - https://github.com/mechef/mechef/wiki/Seller-User-Stories

**Comment by yodhavee** [comment]
@Tzuzee , @pptang , @nkfly ,

Want to check again about this. I don't think we need account registration feature at the moment. The main reason is that I believe for now we want it to be closed group with trusted sellers to try our system. So we can provide login credential to them. Allowing anyone who have link to do the registration will make it harder to control our seller quality.

With the reason above, I don't think we need this feature now. What do you think?

**Comment by Tzuzee** [comment]
I agree we can manually generate an account for internal Alpha sellers, for now. However, we do need account management for our MVP, so I think this feature is still pretty high on the priority list, just lower than the ones that are essential for successfully placing and receiving an order.
