### ISSUE TITLE
Seller can change UI language between English and Japanese

### ISSUE THREAD

**Issue by yodhavee** [mechef/mechef#30]

**Comment by yodhavee** [comment]
This is a good reading for reference on how we should design the website. Personally I think doing subdomain for different language look good.

What do you think @Tzuzee , @pptang , @nkfly ?

**Comment by Tzuzee** [comment]
@yodhavee Did you mean subdomain like www.jp.mechef.com? or did you mean different paths www.mechef.com/jp/xxxxx ?

**Comment by yodhavee** [comment]
oh shoot! I forgot the link. http://searchengineland.com/the-ultimate-guide-to-multilingual-and-multiregional-seo-157838  But yes, I think we should get either

1. subdomains
2. subdirectories

I personally prefer subdirectories because it's easier to parse URL in different tools which can help boost SEO. but please share if you have any preference or any technical constrains.
